version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=your-openai-api-key
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
